default: &default
  adapter: postgresql
  encoding: utf8
  username: <%= ENV.fetch('POSTGRES_USER', 'postgres') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD', 'password') %>
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
development:
  <<: *default
  database: app_development
  host: <%= ENV.fetch('DATABASE_HOST', 'db') %>
test:
  <<: *default
  database: app_test
  host: <%= ENV.fetch('DATABASE_HOST', 'db') %>
production:
  <<: *default
  database: app_production
  url: <%= ENV.fetch('DATABASE_URL') %>