version: "3"
services:
  db:
    dns: 8.8.8.8
    env_file: .env
    image: postgres:10.5
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data
  web:
    dns: 8.8.8.8
    build:
      context: .
      args:
        DOMAIN: $DOMAIN
        RAILS_ENV: $RAILS_ENV
    env_file: .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/app
    depends_on:
      - db
volumes:
  database: