version: "3"
services:
  db:
    dns: 8.8.8.8
    env_file: .env
    image: postgres:10.5
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data
  redis:
    image: redis:5.0.3
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis:/data
  web:
    dns: 8.8.8.8
    build:
      context: .
      args:
        DOMAIN: $DOMAIN
        RAILS_ENV: $RAILS_ENV
        CREDENTIAL: $CREDENTIAL
    env_file: .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
volumes:
  database:
  redis:
